---
title           : "My preregistration for Kruger National Park Animal Study"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Lauren Gill
    affiliation : 1
  - name        : Second Authour
    affiliation : "1"

affiliation:
  - id          : 1
    institution : University of British Columbia

output: prereg::prereg_pdf
---

How I got here --> installed pre reg package, create RmD and then choose from template and then choose this one

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->

## Data collection

**Yes**, data has already been collected for this study,

## Hypothesis

Animals will prefer dirt roads in Kruger National Park, and therefore have more herd sightings on dirt roads.

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

The dependent variable is the presence or absence of an animal herd.

## Conditions

The conditions depend on whether the animals were sited on a dirt road or a tarmac road

## Analyses

First, I will clean the data for my analyses. Initially the data was collected depending on herd size (either \>6 animals or \<6 animals) but for this analysis I will simply need whether the animal herd was present or absent on the dirt road. Therefore I will turn the data into 0s and 1s for presence absence, and then construct a graph to display the results.

## Outliers and exclusions

I will not consider outliers in this dataset

## Sample size

The sample size will be the numbers of observations recorded on dirt roads, in this data set they recorded 770 observations.

## Study type

Class project or assignment

# References

<https://datadryad.org/stash/dataset/doi:10.5061/dryad.bcc2fqzd1>

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
